#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <wx/filedlg.h>
#include <wx/wfstream.h>
#include <wx/log.h> 

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void OpenFile( wxCommandEvent& event );
		void Revert( wxCommandEvent& event );
		void Recount_Axes( wxScrollEvent& event );
		void Change_Angle( wxScrollEvent& event );
		void Move_X( wxScrollEvent& event );
		void Move_Y( wxScrollEvent& event );
		void Interpolate( wxCommandEvent& event );
		wxImage NearestNeighborInterpolation(const wxImage& inputImage, int newWidth, int newHeight);
		wxImage BilinearInterpolation(const wxImage& image, float newWidth, float newHeight);
		void SaveFile( wxCommandEvent& event );
		void Animate( wxCommandEvent& event );

		void Repaint();

		void MaskReflect(double angle);
		void Extend();

		void Reflect(double angle);

		wxImage original;
		wxImage copy;
		wxImage extended;
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

};

#endif // __GUIMyFrame1__
